# -*- coding: utf-8 -*-
"""445 AutoArima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZV2rJZzEnU8Jzi3rRuBjXo9mRS47bbUw
"""

import pandas as pd
import numpy as np
from pmdarima.arima import auto_arima

!pip install pmdarima

from google.colab import drive
drive.mount('/content/drive')

csv_location = './drive/MyDrive/445/channel_5.csv' # Projector Channel

csv_as_dataframe = pd.read_csv(csv_location, header=0)

csv_as_dataframe.columns = ['timestamp', 'load']
csv_as_dataframe = csv_as_dataframe.set_index('timestamp')

csv_as_dataframe.head()

len(csv_as_dataframe)

X = csv_as_dataframe.index.to_numpy()
y = csv_as_dataframe['load'].to_numpy()
print(X[0:10])
print(y[0:10])

x_train = X[0:20000]
y_train = y[0:20000]
x_test = X[20000:21000]
y_test = y[20000:21000]

len(x_train)

len(x_test)

# Create a DataFrame with the timestamp and load values
df = pd.DataFrame({'timestamp': x_train, 'load': y_train})

# Train an ARIMA model using auto_arima
model = auto_arima( 
    df["load"], 
    start_p=1, 
    start_q=1,
    test='adf',       # use adftest to find optimal 'd'
    max_p=5, max_q=5, # maximum p and q
    m=1,              # frequency of series
    d=None,           # let model determine 'd'
    seasonal=True,   # No Seasonality
    start_P=0, 
    D=0, 
    trace=True,
    error_action='ignore',  
    suppress_warnings=True, 
    information_criterion='aic',
    stepwise=True
)
print(model.summary())

